# Generated by Django 3.2.7 on 2022-04-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectheading', models.CharField(default='PROJECT-HEADING', max_length=100, verbose_name='Project-Heading')),
                ('projectdescription', models.CharField(default='Project-Description', max_length=255, verbose_name='Project-Description')),
                ('technologiesused', models.CharField(default='Technologies-Used', max_length=255, verbose_name='Technologies-Used')),
                ('githublinkproject', models.CharField(default='githublink', max_length=255, verbose_name='Github-Link-Project')),
                ('herokulinkproject', models.CharField(default='heroku-link', max_length=255, verbose_name='Herokulink-Project')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
