# Generated by Django 3.2.7 on 2022-04-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220407_0805'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='project',
        ),
    ]
