# Generated by Django 3.2.7 on 2022-04-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='projects',
        ),
    ]
