# Generated by Django 3.2.7 on 2022-04-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=40, verbose_name='Name')),
                ('designation', models.CharField(default='Annonymous', max_length=60, verbose_name='Designation')),
                ('githublink', models.CharField(default='githublink', max_length=100, verbose_name='GitHubLink')),
                ('linkedinlink', models.CharField(default='linkedinlink', max_length=100, verbose_name='LinkedinLink')),
                ('portfoliolink', models.CharField(default='portfoliolink', max_length=100, verbose_name='Portfoliolink')),
                ('address', models.CharField(db_index=True, default='Address', max_length=255, verbose_name='Address')),
                ('cellnumber', models.PositiveIntegerField(db_index=True, verbose_name='CellNumber')),
            ],
            options={
                'db_table': 'header',
            },
        ),
    ]
