# Generated by Django 3.2.7 on 2022-04-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='cellnumber',
            field=models.IntegerField(db_index=True, verbose_name='CellNumber'),
        ),
    ]
