# Generated by Django 3.2.7 on 2022-04-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_alter_header_cellnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='email',
            field=models.EmailField(db_index=True, default='Email', max_length=255, verbose_name='Email'),
        ),
    ]
