# Generated by Django 3.2.7 on 2022-04-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(default='Work-Experience', max_length=255, verbose_name='Work-Experience')),
                ('jobrole1', models.CharField(default='Job-Role', max_length=255, verbose_name='Job-Role-1')),
                ('jobrole2', models.CharField(default='Job-Role', max_length=255, verbose_name='Job-Role-2')),
                ('jobrole3', models.CharField(default='Job-Role', max_length=255, verbose_name='Job-Role-3')),
            ],
            options={
                'db_table': 'workexperience',
            },
        ),
    ]
