# Generated by Django 3.2.7 on 2022-04-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workexperience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='job',
            field=models.CharField(default='Work-Experience', max_length=255, verbose_name='Work-Exp'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='jobrole1',
            field=models.CharField(default='Job-Role1', max_length=255, verbose_name='Job-Role-1'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='jobrole2',
            field=models.CharField(default='Job-Role2', max_length=255, verbose_name='Job-Role-2'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='jobrole3',
            field=models.CharField(default='Job-Role3', max_length=255, verbose_name='Job-Role-3'),
        ),
    ]
