# Generated by Django 3.2.7 on 2022-04-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skills',
            table='skills',
        ),
    ]
