# Generated by Django 3.2.7 on 2022-04-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skills_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
