# Generated by Django 3.2.7 on 2022-04-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skill',
            table='skill',
        ),
    ]
