# Generated by Django 3.2.7 on 2022-04-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduheading', models.CharField(default='Eduction-Heading', max_length=100, verbose_name='Education-Heading')),
                ('edudescription', models.CharField(default='Education-Description', max_length=255, verbose_name='Educaiton-description')),
            ],
            options={
                'db_table': 'education',
            },
        ),
    ]
