# Generated by Django 3.2.7 on 2022-04-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='edudescription',
        ),
        migrations.AddField(
            model_name='education',
            name='edudescription1',
            field=models.CharField(default='Education-Description', max_length=255, verbose_name='Educaiton-description1'),
        ),
        migrations.AddField(
            model_name='education',
            name='edudescription2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Education-Description2'),
        ),
        migrations.AddField(
            model_name='education',
            name='edudescription3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Education-Description3'),
        ),
    ]
